"""The Ayah model.

Quranic text is never generated by this application. It is loaded verbatim from
data/al_fatihah.json, which is produced by `python run.py fetch-text` from a
published Quran edition (or written by hand from a printed mushaf).
"""

from __future__ import annotations

import re
import unicodedata
from typing import Optional

from pydantic import BaseModel, Field, field_validator

# Arabic block ranges that legitimately appear in Uthmani Quranic text.
_ARABIC_RANGES = (
    (0x0600, 0x06FF),  # Arabic
    (0x0750, 0x077F),  # Arabic Supplement
    (0x08A0, 0x08FF),  # Arabic Extended-A (Quranic annotation signs)
    (0xFB50, 0xFDFF),  # Arabic Presentation Forms-A
    (0xFE70, 0xFEFF),  # Arabic Presentation Forms-B
)

_ARABIC_INDIC_DIGITS = "٠١٢٣٤٥٦٧٨٩"


def is_arabic_char(char: str) -> bool:
    code = ord(char)
    return any(low <= code <= high for low, high in _ARABIC_RANGES)


def arabic_ratio(text: str) -> float:
    """Fraction of non-space characters that belong to an Arabic block."""
    letters = [c for c in text if not c.isspace()]
    if not letters:
        return 0.0
    return sum(1 for c in letters if is_arabic_char(c)) / len(letters)


def to_arabic_digits(number: int) -> str:
    return "".join(_ARABIC_INDIC_DIGITS[int(d)] for d in str(number))


def strip_tashkeel(text: str) -> str:
    """Remove combining marks - used for width estimates and diagnostics only."""
    return "".join(c for c in text if not unicodedata.combining(c))


class Ayah(BaseModel):
    number: int = Field(ge=1)
    arabic: str
    urdu_translation: str
    recitation: Optional[str] = None
    urdu_audio: Optional[str] = None
    transliteration: Optional[str] = None
    english_translation: Optional[str] = None

    @field_validator("arabic")
    @classmethod
    def _validate_arabic(cls, value: str) -> str:
        text = value.strip()
        if not text:
            raise ValueError("Arabic text is empty")
        if arabic_ratio(text) < 0.8:
            raise ValueError(
                "Arabic text does not look like Arabic script "
                f"(only {arabic_ratio(text):.0%} of its characters are Arabic)"
            )
        return text

    @field_validator("urdu_translation")
    @classmethod
    def _validate_urdu(cls, value: str) -> str:
        text = value.strip()
        if not text:
            raise ValueError("Urdu translation is empty")
        if arabic_ratio(text) < 0.6:
            raise ValueError(
                "Urdu translation does not look like Urdu script "
                f"(only {arabic_ratio(text):.0%} of its characters are in the Arabic block)"
            )
        return text

    @property
    def padded_number(self) -> str:
        return f"{self.number:03d}"

    @property
    def arabic_number(self) -> str:
        """Ayah number in Arabic-Indic digits, e.g. 3 -> '٣'."""
        return to_arabic_digits(self.number)

    @property
    def word_count(self) -> int:
        return len([w for w in re.split(r"\s+", self.arabic) if w])

    def summary(self) -> str:
        plain = strip_tashkeel(self.arabic)
        return f"Ayah {self.number}: {plain[:46]}{'...' if len(plain) > 46 else ''}"
